services:
  web:
    build: .
    restart: always
    expose:
      - 8000
    image: web:django
    volumes:
      - static_volume:/crm/BalqaimaqCRM/staticfiles
      - media_volume:/crm/BalqaimaqCRM/mediafiles
    container_name: django_container
    command: sh -c "cd BalqaimaqCRM && python manage.py collectstatic --noinput && gunicorn -w 5 --bind 0.0.0.0:8000 BalqaimaqCRM.wsgi"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/crm/BalqaimaqCRM/staticfiles
      - media_volume:/crm/BalqaimaqCRM/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
