services:
  web:
    build: .
    restart: always
    volumes:
      - .:/django
      - static-data:/django/BalqaimaqCRM/staticfiles
    ports:
      - 8001:8001
    image: web:django
    container_name: django_container
    command: sh -c "cd BalqaimaqCRM && gunicorn -w 5 --bind 0.0.0.0:8001 BalqaimaqCRM.wsgi"
    env_file:
      - .env
    depends_on:
      - db
    links:
       - db:db
    networks:
       - djangonetwork
  db:
    image: postgres:14.5
    restart: always
    volumes:
    - ./BalqaimaqCRM/data/db:/var/lib/postgresql/data:z
    env_file:
      - .env
    networks:
    - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  static-data:
