# Generated by Django 5.1 on 2024-12-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Номер телефона')),
                ('password', models.CharField(default='12345678', max_length=100, verbose_name='Пароль')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая сумма заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.client')),
            ],
            bases=('clients.client',),
        ),
    ]
