# Generated by Django 5.1 on 2024-12-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Номер телефона'),
        ),
    ]
