# Generated by Django 5.1 on 2024-11-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_worker_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.client')),
            ],
            bases=('clients.client',),
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_worker',
        ),
    ]
