# Generated by Django 5.1 on 2024-11-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_worker_remove_client_is_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
