# Generated by Django 5.1 on 2024-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая сумма заказов'),
        ),
    ]
