# Generated by Django 5.1 on 2024-11-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Общая сумма заказов'),
        ),
    ]
