# Generated by Django 5.1 on 2024-08-30 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('stage', models.CharField(choices=[('1', 'Упоковка'), ('2', 'Готов к выдаче'), ('3', 'Доставляется'), ('4', 'Завершен')], max_length=20, verbose_name='Этап заказа')),
                ('type_of_payment', models.CharField(choices=[('1', 'Kaspi QR'), ('2', 'Перевод'), ('3', 'Наличные')], max_length=20, verbose_name='Тип оплаты')),
                ('type_of_order', models.CharField(choices=[('1', 'Online'), ('2', 'Offline')], max_length=20, verbose_name='Тип заказа')),
                ('review', models.TextField(max_length=200, verbose_name='Отзыв клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
            ],
        ),
    ]
