# Generated by Django 5.1 on 2024-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Отзыв клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('1', 'Упаковка'), ('2', 'Готов к доставке'), ('3', 'Доставляется'), ('4', 'Завершен')], default='Упаковка', max_length=20, verbose_name='Этап заказа'),
        ),
    ]
