# Generated by Django 5.1 on 2024-12-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.combo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='orders.order')),
            ],
        ),
    ]
