# Generated by Django 5.1 on 2024-09-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_price_alter_order_review_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('1', 'Упаковка'), ('2', 'Готов к доставке'), ('3', 'Доставляется'), ('4', 'Завершен')], default='1', max_length=20, verbose_name='Этап заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_order',
            field=models.CharField(choices=[('1', 'Онлайн'), ('2', 'Оффлайн')], max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='storage.product', verbose_name='Продукт'),
        ),
    ]
