# Generated by Django 5.1 on 2024-11-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_worker_remove_client_is_worker'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='clients.worker', verbose_name='Рабочий'),
        ),
    ]
