# Generated by Django 5.1 on 2025-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10, verbose_name='Количество'),
        ),
    ]
