# Generated by Django 5.1 on 2024-11-04 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_supply_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
