# Generated by Django 5.1 on 2024-08-31 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_active'),
        ('storage', '0002_alter_product_amount_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='storage.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='clients.client', verbose_name='Рабочий'),
        ),
    ]
