# Generated by Django 5.1 on 2024-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_created_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
