# Generated by Django 5.1 on 2025-01-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_combo_products_alter_productsincombo_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(through='storage.ProductsInCombo', to='storage.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='productsincombo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.combo'),
        ),
        migrations.AlterField(
            model_name='productsincombo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Продукт'),
        ),
    ]
