# Generated by Django 5.1 on 2025-01-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_combo_products_alter_productsincombo_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsincombo',
            name='combo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage.combo'),
        ),
    ]
